### ISSUE TITLE
win10:cygwin, can not create version.cpp

### ISSUE THREAD

**Issue by sunyuyangg555** [dspinellis/cscout#15]
sed： version.cpp：No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
Makefile:287: dep/md5.d: No such file or directory
Makefile:287: dep/attr.d: No such file or directory
Makefile:287: dep/call.d: No such file or directory
Makefile:287: dep/cscout.d: No such file or directory
Makefile:287: dep/ctag.d: No such file or directory
Makefile:287: dep/ctconst.d: No such file or directory
Makefile:287: dep/ctoken.d: No such file or directory
Makefile:287: dep/debug.d: No such file or directory
Makefile:287: dep/dirbrowse.d: No such file or directory
Makefile:287: dep/eclass.d: No such file or directory
Makefile:287: dep/error.d: No such file or directory
Makefile:287: dep/fcall.d: No such file or directory
Makefile:287: dep/fchar.d: No such file or directory
Makefile:287: dep/fdep.d: No such file or directory
Makefile:287: dep/fileid.d: No such file or directory
Makefile:287: dep/filemetrics.d: No such file or directory
Makefile:287: dep/filequery.d: No such file or directory
Makefile:287: dep/fileutils.d: No such file or directory
Makefile:287: dep/funmetrics.d: No such file or directory
Makefile:287: dep/funquery.d: No such file or directory
Makefile:287: dep/gdisplay.d: No such file or directory
Makefile:287: dep/globobj.d: No such file or directory
Makefile:287: dep/html.d: No such file or directory
Makefile:287: dep/idquery.d: No such file or directory
Makefile:287: dep/logo.d: No such file or directory
Makefile:287: dep/macro.d: No such file or directory
Makefile:287: dep/mcall.d: No such file or directory
Makefile:287: dep/metrics.d: No such file or directory
Makefile:287: dep/obfuscate.d: No such file or directory
Makefile:287: dep/option.d: No such file or directory
Makefile:287: dep/os.d: No such file or directory
Makefile:287: dep/pager.d: No such file or directory
Makefile:287: dep/pdtoken.d: No such file or directory
Makefile:287: dep/pltoken.d: No such file or directory
Makefile:287: dep/ptoken.d: No such file or directory
Makefile:287: dep/query.d: No such file or directory
Makefile:287: dep/simple_cpp.d: No such file or directory
Makefile:287: dep/sql.d: No such file or directory
Makefile:287: dep/stab.d: No such file or directory
Makefile:287: dep/tchar.d: No such file or directory
Makefile:287: dep/timer.d: No such file or directory
Makefile:287: dep/token.d: No such file or directory
Makefile:287: dep/tokid.d: No such file or directory
Makefile:287: dep/tokmap.d: No such file or directory
Makefile:287: dep/type.d: No such file or directory
Makefile:287: dep/workdb.d: No such file or directory
Makefile:287: dep/css.d: No such file or directory
Makefile:287: dep/eval.d: No such file or directory
Makefile:287: dep/logo.d: No such file or directory
Makefile:287: dep/parse.d: No such file or directory
Makefile:287: dep/tokname.d: No such file or directory
Makefile:287: dep/version.d: No such file or directory
make: *** No rule to make target 'dep/version.d'。

**Comment by dspinellis** [comment]
You must compile the project from a Git clone.

**Comment by dspinellis** [comment]
The program can now be compiled even from a zip archive.
