### ISSUE TITLE
Unable to open include file

### ISSUE THREAD

**Issue by svnpenn** [dspinellis/cscout#16]
I am getting this error, I see no `-I` type options to add a directory of header files

**Comment by dspinellis** [comment]
You need to include it through the `includepath` pragma.  Please read the documentation; the interface of _CScout_ is not compatible with that of a C compiler, because it has to process entire projects at one go.

**Comment by svnpenn** [comment]
@dspinellis um, no? I am not going to add a pragma to every source file just to use this program.

I’ll just stick to the superior http://github.com/include-what-you-use/include-what-you-use

Also, in the future it would be helpful to actually link to something rather than saying essentially, RTFM

**Comment by svnpenn** [comment]
@dspinellis um, no? I am not going to add a pragma to every source file just to use this program.

I’ll just stick to the superior http://github.com/include-what-you-use/include-what-you-use

Also, in the future it would be helpful to actually link to something rather than saying essentially, RTFM

http://spinellis.gr/cscout/doc/pragma.html

**Comment by dspinellis** [comment]
Of course you don't have to modify the C files.  You create a top level file with the pragmas required.  See

* http://www.spinellis.gr/cscout/doc/flow.html
* http://www.spinellis.gr/cscout/doc/wsp.html
* http://www.spinellis.gr/cscout/doc/csmake.html
