### ISSUE TITLE
Cross compiler support

### ISSUE THREAD

**Issue by svnpenn** [dspinellis/cscout#17]
Upon running `csmake`, I get this error:

~~~
Unable to open /tmp/spy-make.3076/rules for reading: No such file or directory
Make sure you have run `make clean' or an equivalent command.
~~~

Upon digging into the source:

http://github.com/dspinellis/cscout/blob/c758472/src/csmake.pl#L67-L70

it appears that GCC, LD and AR are hard coded. This would mean that cross
compilers such as x86_64-w64-mingw32-gcc are not supported. Please advise if
this is the case, or if a setting is available to change the compiler.

**Comment by dspinellis** [comment]
Indeed the compiler names are hard-coded.  You can add more names in the region you identify, or add an option for more names.  Keep in mind that compilers with options different from the ones handled may also require further adjustments.

The most robust way to use CScout is through a workspace definition.  The _csmake_ way can save you a lot of work, but as you point out, it doesn't always work.

**Comment by svnpenn** [comment]
@dspinellis can you show what one might look like? I see this page:

http://spinellis.gr/cscout/doc/wsp.html

but it is not clear.

**Comment by dspinellis** [comment]
The workspace definition is a comprehensive way to define the include path, the predefined macros, and the working directory for each C file, without a lot of repetition.

See also the detailed example at the end of page http://www.spinellis.gr/cscout/doc/wspd.html

What would help you to understand it better?

**Comment by svnpenn** [comment]
Where is the compiler defined?

**Comment by dspinellis** [comment]
There is not need to define a compiler.  _CScout_ will process the files defined in a workspace on its own.

**Comment by svnpenn** [comment]
What a nightmare this tool this. I will stick to
http://github.com/include-what-you-use/include-what-you-use

With that tool, all you do is:

    make -k CC=include-what-you-use \
    CFLAGS='-isystem C:/cygwin64/usr/x86_64-w64-mingw32/sys-root/mingw/include'

and done.

**Comment by dspinellis** [comment]
What are you trying to accomplish?  Maybe _CScout_ is not the right tool for your task.

**Comment by svnpenn** [comment]
I am trying to remove unused includes and/or optimize includes for space/speed

**Comment by dspinellis** [comment]
Once you get the _CScout_ to process your project you'll see warnings, [like the following](http://www.dmst.aueb.gr/dds/cscout/doc/run.html):
```
/home/dds/src/cscout/example/awk/main.c:29: unused included file /home/dds/src/cscout/include/ctype.h
```

However, the analysis you require does not need the whole project to be processed in one go, so the configuration of _include-what-you-use_ is bound to be simpler.

Would it help you if I added to _csmake_ the ability to use a specified C compiler?

**Comment by svnpenn** [comment]
It might, as currently I see no way to get this program working on my system without modifying the source

**Comment by dspinellis** [comment]
I pushed a change.  Please pull it and try
```
make clean
CC=x86_64-w64-mingw32-gcc csmake
```

**Comment by svnpenn** [comment]
@dspinellis I had a change to test this again, and now I cant even get Cscout to
build. Here is the issue:

~~~
wget http://downloads.sourceforge.net/project/hsqldb/hsqldb/hsqldb_2_3/hsqldb-2.3.3.zip || curl -O http://downloads.sourceforge.net/project/hsqldb/hsqldb/hsqldb_2_3/hsqldb-2.3.3.zip
--2016-07-12 20:37:30--  http://downloads.sourceforge.net/project/hsqldb/hsqldb/hsqldb_2_3/hsqldb-2.3.3.zip
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 52.85.142.119, 52.85.142.231, 52.85.142.62, ...
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|52.85.142.119|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://downloads.sourceforge.net/#!/project/hsqldb/hsqldb/hsqldb_2_3/hsqldb-2.3.3.zip [following]
--2016-07-12 20:37:30--  http://downloads.sourceforge.net/
Reusing existing connection to downloads.sourceforge.net:80.
HTTP request sent, awaiting response... 200 OK
Length: 639 [text/html]
Saving to: ‘hsqldb-2.3.3.zip’

hsqldb-2.3.3.zip    100%[===================>]     639  --.-KB/s    in 0s

2016-07-12 20:37:30 (7.68 MB/s) - ‘hsqldb-2.3.3.zip’ saved [639/639]
~~~

Few things:

1. It seems like a bad idea to put wget into a makefile. It should not be
Cscouts job to install other software. The makefile should check should check
for hsqldb files and fail gracefully if not found.

2. If you insist on doing this, you should use a more robust wget command, such
as `wget -nc` or wget `-N`

3. SourceForge. SourceForge SourceForge SourceForge. What an awful shithole of a
website. I would not use SourceForge unless I had no other choice. I would
seriously consider finding another library to replace HSQLDB, that does not rely
on SourceForge.

**Comment by dspinellis** [comment]
I can certainly replace the HSQLDB installation with a simple check.  Would it be easy for you to install it on your system in another way?

**Comment by dspinellis** [comment]
Also, HSQLDB is only used for testing, so I can make testing an optional step.

**Comment by svnpenn** [comment]
Well, I was assuming it just needs to be unzipped. Does it actually need to be compiled?

**Comment by svnpenn** [comment]
Well, I was assuming it just needs to be unzipped. Does it actually need to be compiled? Here is an idea, this is the way FFmpeg setup works: if HSQLDB files are not found, then that part of the process is skipped and normal Cscout build continues

**Comment by dspinellis** [comment]
Yes, unzipping to a known location is all that's needed.  How would you expect CSCout to locate its installation location?

**Comment by svnpenn** [comment]
HSQLDB should be installed in `$prefix`. This is a standard for C programs. For example, on my system prefix is:

    /usr/x86_64-w64-mingw32/sys-root/mingw

where library files can be found

    /usr/x86_64-w64-mingw32/sys-root/mingw/include
    /usr/x86_64-w64-mingw32/sys-root/mingw/lib

However typically this will look more like:

    /usr
    /usr/lib
    /usr/include

or the user can choose to install in /usr/local:

    /usr/local
    /usr/local/lib
    /usr/local/include

in which case Cscout would need to be called:

    make PREFIX=/usr/local

**Comment by dspinellis** [comment]
I pushed a change that increases the flexibiliy regarding the use of HSQLDB.  

NB Please use a separate issue for each problem.

**Comment by svnpenn** [comment]
@dspinellis still no dice. Here is hello.c:

~~~
#include <stdio.h>
int main() {
  puts("hello world");
}
~~~

and makefile:

~~~
hello: hello.o
~~~

I can run csmake as you instructed:

~~~
$ CC=x86_64-w64-mingw32-gcc csmake
x86_64-w64-mingw32-gcc    -c -o hello.o hello.c
x86_64-w64-mingw32-gcc   hello.o   -o hello
~~~

but the following cscout call fails:

~~~
$ cscout make.cs
No options file found; will use default options.
No ACL found.  Only localhost access will be allowed.
Processing project hello
Processing /Desktop/etc/hello.c
/Desktop/etc/make.cs:83: warning: Duplicate (different) macro definition of macro __has_include_next
/usr/x86_64-w64-mingw32/sys-root/mingw/include/_mingw.h:542: error: syntax error

Segmentation fault (core dumped)
~~~

**Comment by dspinellis** [comment]
I don't have your `_mingw.h`, but I guess it uses a compiler extension that CScout doesn't support directly. Typically it's easy to sidestep such problems by defining a suitable macro.

**Comment by svnpenn** [comment]
@dspinellis thanks for all the help, but I think I’m done here. Every issue I run into is met with a suggestion that I don’t know how to implement. It is getting old.

**Comment by dspinellis** [comment]
No problem.  Thanks for trying and good luck with what you're trying to achieve.
