### ISSUE TITLE
Portability improvement (autotools, pkg-config, cmake, …)

### ISSUE THREAD

**Issue by nado** [dspinellis/cscout#19]
Hi,

Would you consider using a Makefile generator or anything making the build process more portable ? As for #18 it helps a lot in the packaging process for any distribution.

In addition of the CC variables, you also have some INSTALL_PREFIX and dependencies variables hardcoded.

**Comment by dspinellis** [comment]
I made the `INSTALL_PREFIX` assignment in the Makefile optional.

I'd welcome a pull request for a proper Makefile generation process. Not sure if I'll find time to write it on my own.  If you submit one, please make sure that it passes a run of `make test` from the top-level directory, and that you also update the documentation.

**Comment by nado** [comment]
Great, thank you already for the `INSTALL_PREFIX` change, and I’ll see if I have some time to do that.
