### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [dspinellis/cscout#20]
Would you like to add more error handling for return values from functions like the following?
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html "Print formatted output") ⇒ [Pager::end](https://github.com/dspinellis/cscout/blob/6ccd564d171f6870fa43e611c32692bca7ea1317/src/pager.cpp#L51 "Display a message")
- [fputs](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fputs.html "Put a string on a stream") ⇒ [html_perror](https://github.com/dspinellis/cscout/blob/a257dde1bcdf6ccf6d87b13eed554451ef03ffcb/src/html.cpp#L254 "Display a system error")

**Comment by dspinellis** [comment]
What use case do you have in mind where this would be important?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by dspinellis** [comment]
I prefer to prioritize based on common sense.

**Comment by elfring** [comment]
Do you care if the desired file output succeeded?

**Comment by dspinellis** [comment]
You fail to understand that in this case output does not go to a file.

**Comment by elfring** [comment]
Would you like to clarify the failure probability for the mentioned HTML output a bit more?
