### ISSUE TITLE
obtaining info in plain text rather than through a browser

### ISSUE THREAD

**Issue by philggithub** [dspinellis/cscout#21]
(Great soft!)
2 questions: 
My interest is in processing potentially large C projects and obtain the static call graph of each in plain text.
1) I've understood how to do that through the browser but it'd be much easier for me to redirect the output of cscout to some plain text file in order to automatically process many projects. How can I do that ?
2) Is there a way to get rid of calls to functions and macros that belong to include'd files?
Thanks!
Philippe

**Comment by dspinellis** [comment]
1. You can create output to save in a database.  If you don't want to involve a database you can process the SQL statements with another tool, or create a plain text back end.
2. You can mark them as read-only and process them accordingly.
