### ISSUE TITLE
Error message interpretation

### ISSUE THREAD

**Issue by gbonnema** [dspinellis/cscout#22]
Hi,

I am refactoring old C code and came across cscout which probably is a big help. I created a specification using the documentation on your website for cscout: 

`workspace xwpe-git {`
`	ro_prefix "/usr/include"`
`	define LIBRARY_DIR 1`
`	project xwpe {`
`		cd "src"`
`		ipath ".."`
`		file we_block.c we_edit.c we_fl_unix.c WeLinux.c we_mouse.c `
`		file we_progn.c we_term.c we_xterm.c we_debug.c WeExpArr.c we_gpm.c `
` 		file we_main.c we_opt.c WeString.c we_unix.c WeXterm.c we_e_aus.c `
`		file we_fl_fkt.c we_hfkt.c we_menue.c we_prog.c WeSyntax.c we_wind.c`
`	}`
`}`

executed `cswc xwpe.cscout > xwpe.cs` and `cscout xwpe.cs`. The output points to an error I do not understand, I print the last few lines.

`/home/data/gbonnema/projects/c/xwpe-guus/src/we_fl_fkt.c:1498: warning: assuming declaration int __builtin_strncpy(...)`
`Done processing file we_fl_fkt.c`
`Processing file we_hfkt.c`
`/usr/local/include/cscout/host-defs.h:289: warning: Duplicate (different) macro definition of macro __has_include_next`
`/usr/include/regex.h:568: error: syntax error`

It seems like there is an error in a library header? Or do I misunderstand the message completely. I checked the regex.h file and do not see the error it refers to. Could you point me in the right direction?

Kind regards, Guus Bonnema.

**Comment by dspinellis** [comment]
It seems there is some code in that location that *CScout* cannot understand. I suggest to examine the code for that error, as documented [here](https://www.spinellis.gr/cscout/faq.html#syntax).

**Comment by gbonnema** [comment]
I followed the instructions to get the preprocessed input, because I don't know which include statement is the cause, and it core-dumps and gives only 1 line of c-program output:

`[gbonnema@maxima xwpe-guus]$ cscout -E problem.cs > prep.c`
`Processing workspace xwpe-git`
`Processing project xwpe`
`Entering directory src`
`Processing file we_hfkt.c`
`/usr/local/include/cscout/host-defs.h:289: warning: Duplicate (different) macro definition of macro `__has_include_next`
`/usr/include/regex.h:568: error: syntax error`
`Segmentation fault (core dumped)`
`[gbonnema@maxima xwpe-guus]$ vi prep.c `
`[gbonnema@maxima xwpe-guus]$ `

The contents of the c-file is: 

`static void _cscout_dummy2(void) { _cscout_dummy2(); }`

Checking out the message a bit closer, I had a look at `/usr/local/include/cscout/host-defs.h` and indeed found multiple definitions of the macro `__has_include_next`, one on line 82 and one on line 288. Why the warning states 289 I don't know.

The same macro name is also used in `csmake-pre-defs.h` on line 82.

Is it possibly an error in the cscout define? Although I can't imagine cscout not being able to define something twice.

**Comment by dspinellis** [comment]
The error must be something different.  Regarding the preprocessing, did you change the `#pragma process` to `#include`?  Your `.cs` file should be something like the following:
```
// workspace xwpe-git
#pragma echo "Processing workspace xwpe-git\n"
#pragma ro_prefix "/usr/include"
// project xwpe
#pragma echo "Processing project xwpe\n"
#pragma project "xwpe"
#pragma block_enter
#pragma echo "Entering directory src
"
#pragma pushd "src"
// file we_hfkt.c
#pragma echo "Processing file we_hfkt.c\n"
#pragma block_enter
#pragma clear_defines
#pragma clear_include
#include "/home/dds/src/awkeg/.cscout/cscout_defs.h"
#define LIBRARY_DIR 1
#pragma includepath ".."
#include "/home/dds/src/awkeg/.cscout/cscout_incs.h"
// NOTE #include here
#include "we_hfkt.c"

#pragma block_exit
#pragma echo "Done processing file we_hfkt.c\n"
#pragma echo "Exiting directory src\n"
#pragma popd
#pragma block_exit
#pragma echo "Done processing project xwpe\n"
#pragma echo "Done processing workspace xwpe-git\n"
```

**Comment by gbonnema** [comment]
Thank you for your swift answers (on a sunday!!). I did indeed forget this statement (replace by include). However, now I have a c file, that compiles. It does not link ofcourse because it needs other programs. If I compile with -c -o everything is fine. I also scanned through the source, but could not find anything amiss. 

I think I wasn't looking in the right place. The error message says something about regex, so the problem has to be with a regular expression. I will dig some more and let you know what I find.

Again, thank you for your responses (and your time!).

Kind regards, Guus.

**Comment by gbonnema** [comment]
I found the error! Thank you for your cooperation. My call to regexec had a wrong number of arguments.

Would it be an idea to show the source code line number + statement of the offending source code as being the culprit? The current message steers you towards a library header that is not wrong at all, but does hint at the error. you just don't know where to look for it. That might help future users (not to mention me ;P).

Thanks again for your effort and for your program. I will close the issue if that indeed solves the problem.

Kind regards Guus.

**Comment by dspinellis** [comment]
A call to regexec had a wrong number of arguments should not be a syntax error. 

Regarding your suggestion, I can envisage a mode where the preprocessed code is saved and the listed, but with typical macro usage this can produce horrendous messages.

Try preprocessing the code (cscout -E), removing `#line` directives, and then processing the result.

**Comment by dspinellis** [comment]
I meant processing the resulting file with *CScout*.  This will give you the exact position where the error occurs.

**Comment by dspinellis** [comment]
Now error messages show offending code as suggested.
