### ISSUE TITLE
-c and -r do not work together

### ISSUE THREAD

**Issue by Guy-Shaw** [dspinellis/cscout#24]
According to this documentation:

  https://www.spinellis.gr/cscout/doc/run.html
  Section: Checking invocation

I should be able to run the command:

  cscout -rc marklar.cs

but all I get is Usage message.

The option processing logic in cscout.cpp clearly forbids this combination.
The cases 'c' and  'r': ... require the variable 'process_mode' to be 0 (pm_unspecified).

Since process_mode is an enum, you must pick one and only one.
There does not seem to be a way to specify a set of process modes.
If process_mode were some set type, like a bitmap, then more than one
can be specified.  That would make the logic for validating combinations
a bit more complicated.

If it is really true that -c and -r are incompatible, then I guess the documentation
needs to be changed, instead.  But it seems to me that -c has implications that
are completely orthogonal to other options, and so needs to be kept track of
separately, not as part of an enum.

-- Guy Shaw

**Comment by dspinellis** [comment]
Thank you for the feedback!  The warning report file (`-r`) will also result in the program exiting, so there is no need to specify the compile-only flag (`-c`).
