### ISSUE TITLE
Syntax error when including complex.h

### ISSUE THREAD

**Issue by jeorsch** [dspinellis/cscout#25]
When trying to process

```C
#include <complex.h>

int main() {
}
```

I get a syntax error for cmathcalls.h. I use glibc version 2.19 and gcc 4.9.2.

Best regards

Georg Geiser

**Comment by dspinellis** [comment]
Hi Georg,

This is to be expected, because CScout currently lacks support for the `_Complex` keyword.  Maybe 

```
#define _Complex
```

would be enough for corresponding programs to compile.

**Comment by jeorsch** [comment]
Hi Diomidis,

Yes, it works. However, e.g. the FFTW library changes its API depending whether complex.h is included or not. Defining _Complex breaks the inclusion of fftw3.h. I can circumvent this for my application by not using FFTW, but maybe a native support of the standard library complex feature in CScout would make sense. There seem to be some more problems when using tgmath.h. I had syntax error when using fabs() in this case. Including math.h instead fixed this problem.

Thanks for your help!

Georg

**Comment by dspinellis** [comment]
Georg, regarding `tgmath.h` either a CScout-specific version of the header file must be provided, or the builtins used in the system-provided one must be defined.

I'm closing this issue and opening issue #26 for the required tasks.
