### ISSUE TITLE
Race condition in csmake rule generation

### ISSUE THREAD

**Issue by pelrun** [dspinellis/cscout#47]
When running csmake against my codebase, the output to the `rules` file from all the concurrent spy processes isn't synchronised, resulting in "BEGIN COMPILE...END COMPILE" blocks appearing in the middle of others, often breaking a random #define line in half.

Ideally each spy invocation should write to an independent temp file, and all the files concatenated at the end of the run.

**Comment by dspinellis** [comment]
Good point!  I assume you're running *csmake* with a `-j` flag?

**Comment by pelrun** [comment]
Not directly, but the project is complicated with all sorts of shenanigans and subordinate make's happening under the hood (I didn't write it :grin: )

**Comment by dspinellis** [comment]
Can you please try the version of *csmake* I just pushed?

**Comment by dspinellis** [comment]
Fixed and tested against `make-j` on the Linux kernel with 3c69031ad5d1941c1381c14f5de6d70dd118c1de.
