### ISSUE TITLE
Program's auditing and licensing server

### ISSUE THREAD

**Issue by username102938** [dspinellis/cscout#63]
What does it mean?

Processing identifiers
100%
Invalid reply from server: [HTTP/1.1 301 Moved Permanently
Date: Sat, 07 Mar 2020 17:03:58 GMT
Server: Apache/2.4.25 (Debian)
Location: https://www.spinellis.gr/cgi-bin/ccheck?h=blink&v=2.7&d=064c3eecf563228f
Content-Length: 288
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.spinellis.gr/cgi-bin/ccheck?h=blink&amp;v=2.7&amp;d=064c3eecf563228f">here</a>.</p>
</body></html>

**Comment by dspinellis** [comment]
I think you're running a legacy unsupported version.

**Comment by username102938** [comment]
Yes, I used a legacy version and got the message listed.
I did some tests and some times, not often, (depends on the tested source code) a connection is established with www.spinellis.gr
What is the purpose of that connection?
Does cscout send the source code to your server for auditing?
If yes, why isn't it written in the documentation?

The important question is: do you have a copy of my source code?
Mr. Spinellis remember that it is copyrighted material.

**Comment by dspinellis** [comment]
The version you appear to be using was only licensed for analyzing and modifying free/Open Source software. If you are using that version of CScout to analyze proprietary software you are in violation of the license's terms; you should have purchased a commercial software license.  Feel free to contact me over email for more information.

**Comment by username102928** [comment]
Version 2.7 is the one currently distributed with FreeBSD.
https://www.freshports.org/devel/cscout/
When I installed it I didn't know it was out of date.
In the README file i read:
"This free unsupported version of CScout is distributed under the terms of the CScout Public License, which is available in the accompanying documentation."
But in the accompanying documentation there is nothing.
I cannot be in violation of a license if it is unspecified.

Mr. Spinellis i ask you again: do you have a copy of my source code?
If yes, I ask you to cancel it now.

**Comment by dspinellis** [comment]
The license is file 54 `share/doc/cscout/license.html` in the link you posted. Its violation is too serious to discuss with anonymous accounts registered only hours ago. You may always contact me over email.
