### ISSUE TITLE
Error Handling behaviour

### ISSUE THREAD

**Issue by StefanosChaliasos** [dspinellis/cscout#66]
Why E_ERR escalates to E_FATAL after 1000 E_ERR errors?

https://github.com/dspinellis/cscout/blob/0549ed2db1d54ac8607894819ffe96dc28131d9b/src/error.cpp#L77

**Comment by dspinellis** [comment]
So that the program exits, rather than producing tons of errors nobody will read. It is the typical behavior of compilers: after a number of errors they quit, based on the idea that one of the reported errors is responsible for a cascade of more ones.
