### ISSUE TITLE
make-version.sh compilation infinite loop

### ISSUE THREAD

**Issue by int3rsys** [dspinellis/cscout#74]
Hi,
I cloned the repo and ran the make command. During the compilation, it entered into an inifinite loop:
`....
sh make-version.sh >version.cpp
: not foundn.sh: 4:
echo Expect 3 shift/reduce conflicts, 64 reduce/reduce conflicts
Expect 3 shift/reduce conflicts, 64 reduce/reduce conflicts
../btyacc/btyacc -d -b eval -p eval_ eval.y
mv -f eval.tab.c eval.cpp
sh make-version.sh >version.cpp
: not foundn.sh: 4:
sh make-version.sh >version.cpp
: not foundn.sh: 4:
sh make-version.sh >version.cpp
: not foundn.sh: 4:
sh make-version.sh >version.cpp
: not foundn.sh: 4:
sh make-version.sh >version.cpp
: not foundn.sh: 4:
sh make-version.sh >version.cpp
: not foundn.sh: 4:
sh make-version.sh >version.cpp
: not foundn.sh: 4:
sh make-version.sh >version.cpp
: not foundn.sh: 4:
sh make-version.sh >version.cpp
: not foundn.sh: 4:
...`

Trying to run 'make clean' afterwards also hits the infinite loop:
`
ilyar@irozents-mobl:/mnt/c/Users/irozents/Downloads/cscout$ make clean
cd src && make clean
make[1]: Entering directory '/mnt/c/Users/irozents/Downloads/cscout/src'
sh make-version.sh >version.cpp
: not foundn.sh: 4:
sh make-version.sh >version.cpp
: not foundn.sh: 4:
sh make-version.sh >version.cpp
: not foundn.sh: 4:
sh make-version.sh >version.cpp
: not foundn.sh: 4:
`

**Comment by hugonad** [comment]
I have the same issue when i try to install with WSL 2
